version: 2
project_name: orion

builds:
  - env:
      - CGO_ENABLED=0
    binary: orion
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X orion/internal/version.Version={{.Version}}
      - -X orion/internal/version.Commit={{.Commit}}
      - -X orion/internal/version.Date={{.Date}}

archives:
  - format: tar.gz
    # Use a standard naming convention to make it easy for install.sh to guess the URL
    # e.g., orion_darwin_arm64.tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
